name: Trigger Partial Build

on:
  - release
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Partial Build
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/kingandpartners/kingandpartners-composer/actions/workflows/partial-build.yml/dispatches \
            -d '{"ref":"main","inputs":{"package_name":"kingandpartners/elastic-press"}}'
